# kate: indent-width 2;

clone_depth: 1

environment:
  matrix:
  - TARGET: desktop
    COMPILER: msvc
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    APPVEYOR_JOB_NAME: windows-gl-msvc2015
  - TARGET: desktop
    COMPILER: msvc
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    APPVEYOR_JOB_NAME: windows-gl-msvc2017
  - TARGET: desktop
    COMPILER: mingw
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    APPVEYOR_JOB_NAME: windows-gl-mingw
  #- TARGET: desktop-gles
    #TARGET_GLES2: ON
    #APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #APPVEYOR_JOB_NAME: windows-gles2-msvc2015
    #COMPILER: msvc
  #- TARGET: desktop-gles
    #TARGET_GLES2: ON
    #APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #APPVEYOR_JOB_NAME: windows-gles2-msvc2017
    #COMPILER: msvc
  - TARGET: desktop-gles
    TARGET_GLES2: OFF
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    APPVEYOR_JOB_NAME: windows-gles3-msvc2015
    COMPILER: msvc
  - TARGET: desktop-gles
    TARGET_GLES2: OFF
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    APPVEYOR_JOB_NAME: windows-gles3-msvc2017
    COMPILER: msvc
  #- TARGET: rt
    #TARGET_GLES2: ON
    #APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #APPVEYOR_JOB_NAME: windows-rt-gles2-msvc2015
  #- TARGET: rt
    #TARGET_GLES2: ON
    #APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #APPVEYOR_JOB_NAME: windows-rt-gles2-msvc2017
  - TARGET: rt
    TARGET_GLES2: OFF
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    APPVEYOR_JOB_NAME: windows-rt-gles3-msvc2015
  - TARGET: rt
    TARGET_GLES2: OFF
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    APPVEYOR_JOB_NAME: windows-rt-gles3-msvc2017

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/415ae90928ba0dbd3df4
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

install:
- cinst ninja
- set PATH=C:/Sys/bin;C:/tools/ninja;%PATH%
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "mingw" pip install codecov
- IF "%TARGET_GLES2%" == "ON" set TARGET_GLES3=OFF
- IF "%TARGET_GLES2%" == "OFF" set TARGET_GLES3=ON

# SDL2
- IF NOT "%TARGET%" == "rt" IF "%COMPILER%" == "msvc" IF NOT EXIST %APPVEYOR_BUILD_FOLDER%\SDL2-devel-2.0.4-VC.zip appveyor DownloadFile http://www.libsdl.org/release/SDL2-devel-2.0.4-VC.zip
- IF NOT "%TARGET%" == "rt" IF "%COMPILER%" == "msvc" 7z x SDL2-devel-2.0.4-VC.zip && ren SDL2-2.0.4 SDL
- IF NOT "%TARGET%" == "rt" IF "%COMPILER%" == "mingw" IF NOT EXIST %APPVEYOR_BUILD_FOLDER%\SDL2-devel-2.0.4-mingw.tar.gz appveyor DownloadFile http://libsdl.org/release/SDL2-devel-2.0.4-mingw.tar.gz
- IF NOT "%TARGET%" == "rt" IF "%COMPILER%" == "mingw" 7z x SDL2-devel-2.0.4-mingw.tar.gz & 7z x SDL2-devel-2.0.4-mingw.tar & ren SDL2-2.0.4 SDL

build_script:
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "msvc" call package\ci\appveyor-desktop.bat
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "mingw" call package\ci\appveyor-desktop-mingw.bat
- IF "%TARGET%" == "desktop-gles" call package\ci\appveyor-desktop-gles.bat
- IF "%TARGET%" == "rt" call package\ci\appveyor-rt.bat

cache:
- SDL2-devel-2.0.4-VC.zip
- SDL2-devel-2.0.4-mingw.tar.gz
